In [2]:
import numpy as np

In [3]:
d = [1, 2, 3]
np.cov(d)

array(1.0)

In [6]:
d-np.mean(d)

array([-1.,  0.,  1.])

In [34]:
X = np.matrix([[3, 5, 1], [9, 1, 4]])
l = np.matrix([[1], [1]])

In [35]:
l

matrix([[1],
        [1]])

In [36]:
l.T

matrix([[1, 1]])

In [46]:
(l*l.T)*X

matrix([[12,  6,  5],
        [12,  6,  5]])

In [38]:
X

matrix([[3, 5, 1],
        [9, 1, 4]])

In [49]:
X - ((l*l.T)*X)/2.0

matrix([[-3. ,  2. , -1.5],
        [ 3. , -2. ,  1.5]])